
package aritmatika.java;
public class AritmatikaJava {
    public static void main(String[] args) {
      
        int a = 3;
        int b =6;
        
       b += a;
        System.out.println(a);
        a -= b;
        System.out.println(a);
        a *= b;
        System.out.println(b);
        a /= b;
        System.out.println(a);
        a %= b;
        System.out.println(b);
        
             // perbandingan
             int NilaiA = 2;
             int NilaiB = 1;
             boolean hasil;
            
             // apakah A lebih besar B
              hasil = NilaiA > NilaiB;
              System.out.println(hasil);
              // apakah A lebih kecil B
              hasil = NilaiA < NilaiB;
              System.out.println(hasil);
              // apakah A lebih besar samadengan B
              hasil = NilaiA >= NilaiB;
              System.out.println(hasil);
              // apakah A lebih keci samadengan B
              hasil = NilaiA <= NilaiB;
              System.out.println(hasil);
              //apakah A sama dengan B
              hasil = NilaiA == NilaiB;
              System.out.println(hasil);
              // apakah A tidak sama dengan B
              hasil = NilaiA != NilaiB;
              System.out.println(hasil);
             
    }
    
}
