
package tipedata.java;
public class TipeDataJava {
    public static void main(String[] args) {
        String nama = "azisah";
        String alamat = "kalukku";
        String hp = "hp";
       char JenisKelamin = 'p';
        int umur = 18;
        double tinggi = 153;
        
        System.out.println("nama"+nama+"alamat"+alamat+"hp"+hp+"JenisKelamin"+JenisKelamin+"umur"+umur+"tinggi"+tinggi);
        
        
        
        
    }
    
}
